### ISSUE TITLE
Aneinanderreihung von Zitaten

### ISSUE THREAD

**Issue by szaiser** [23x/stoll-klangbrett#14]
Beispielsweise das Zitat 1938 ist für sich genommen nicht so der Knaller. Aber man könnte sicher lustige Texte kreieren, wenn durch aufeinanderfolgendes klicken die Zitate in eine Warteschlange eingefügt würden. Zusätzlich wäre eine Restdauer Anzeige sowie die Anzeige der Gesamtlänge der einzelnen Zitate sinnvoll.

**Comment by lawl** [comment]
Das geht seit Ewigkeiten: http://sicherheit.reichsinter.net/stoll/#ameisen,geheimwissen

**Comment by jomo** [comment]
Muss man wissen!
