### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by dex2000** [23x/stoll-klangbrett#17]
Siehe Betreff ;)

    No such site at :443

**Comment by jomo** [comment]
DAS STOLL KLANGBRETT WAR SCHON IMMER UNTER http://STOLL.REICHSINTER.NET  ZU ERREICHEN

**Comment by dex2000** [comment]
Das ist fein, dann sollte man aber den Link oben auch ändern.

**Comment by chpio** [comment]
Ja, das sollte wohl irgendwer mal machen.

**Comment by lubiana** [comment]
es hat sogar irgendwer gemacht

**Comment by ajs124** [comment]
Jetzt ist das auch down :sob:
